default: &default
  adapter: postgresql
  encoding: unicode
  host: bip-db
  username: development
  password:
  pool: 5

development:
  <<: *default
  database: bip_dev
  password: password

test:
  <<: *default
  database: bip_test
  password: password
